spring:
  application:
    name: learn-spring-securit
  # ?????

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
mybatis-plus:
  type-aliases-package: com.lin.ssc.pojo
  configuration:
    #mybatis-plus???????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #??banner
    banner: false

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
